dist: bionic
language: csharp
mono: none
dotnet: 2.1.502

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - secure: "GTVJBXNVOpDLCAl05a+njx/S0aNID/3CNoqJ8JD8/tmXOqdnR2TQY+HGZm7UF22EWP662KQTxbBtXHinb7UleaQ9mDN2do8suAHSaf8YDqPX3YPqnsi38jzIMz3jeb627uhTGwVPwvus/Vp0IcMgPduzZSJcTWNv0c6hsf2tne2suEm3X/+adyJWoFs3/HvmKQIMLAI38tx0CyZMI59dRcGO72cJ9+t90IbmRsnCty1+Y2Uiq1Z/kZHkQ9zdnvdc8u7P+4dHVeku1+cRKOULGWimDW9BJB/1kDti22jEYC6S6Pg8ddX580GY/aq0W45rq+NUMm6Qo80LgPFz+Bhtf/9nWS+mH8xyaIbVdOVc2GSPwQFP0ybxdd3O7ccZFvXlihyAoSm9Iey9GkkT+AZHtfMQMRvouCvHap7WZoO259i68BnwDN+vb4yL+TScbW+S2ym+mMyxVU1CECSMgKaYZEoBZyXr+b0lKPuVbwI9F49aIS15kG+j77Wey+6HGEa+u4cXfIJiqPvY2g0vU/2TVYPfqZ3H2bftKAANIC7yibdgJgryqVzwir3+ujjGhkGR9nWmOiDpH5j146tdKx4A25FM1KDeTYsN6umvRyAPmZRpZSxb0detSbdvCtH369+8JWFuZUKfmvRIKshrn+A1iiGynCQ3s1K/lf50hWXX5Xg="

script:
  - pushd test/Tmds.LibC.Tests && dotnet test && popd
  - dotnet pack src/Tmds.LibC --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER" --output .

after_success:
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.LibC/Tmds.LibC.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
     fi'
