name: Build
on: [push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v2

    - run: |
        pushd test/Tmds.LibC.Tests && dotnet test && popd
        dotnet pack src/Tmds.LibC --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER" --output .

    - run: |
        curl -H "X-NuGet-ApiKey: ${{ secrets.NUGET_APIKEY }}" -T Tmds.LibC.*.nupkg https://www.myget.org/F/tmds/api/v2/package
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
